# Generated by Django 4.1.11 on 2023-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='Cliente',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_premium',
            field=models.BooleanField(default=False),
        ),
    ]
