# Generated by Django 4.1.11 on 2023-10-13 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_cliente_carrito_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturacion',
            name='ciudad_envio',
        ),
        migrations.RemoveField(
            model_name='facturacion',
            name='direccion_envio',
        ),
        migrations.RemoveField(
            model_name='facturacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='facturacion',
            name='medio_entrega',
        ),
        migrations.RemoveField(
            model_name='facturacion',
            name='total',
        ),
        migrations.AddField(
            model_name='facturacion',
            name='cvv_tarjeta',
            field=models.CharField(default='cvv_tarjeta', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturacion',
            name='vencimiento_tarjeta',
            field=models.CharField(default=datetime.datetime(2023, 10, 13, 18, 23, 21, 969384, tzinfo=datetime.timezone.utc), max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medioentrega',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogo.cliente'),
            preserve_default=False,
        ),
    ]
