# Generated by Django 4.1.11 on 2023-10-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_remove_facturacion_ciudad_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='vencimiento_tarjeta',
            field=models.DateField(),
        ),
    ]
