# Generated by Django 4.1.11 on 2023-10-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_facturacion_vencimiento_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medioentrega',
            name='entrega',
            field=models.CharField(default='Entrega Normal', max_length=1000),
        ),
        migrations.AlterField(
            model_name='medioentrega',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
